name: build-frontend
on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 0 * * *"
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
      # cd frontend/
      - name: NPM or Yarn install with caching 📦
        uses: bahmutov/npm-install@v1
        with:
          working-directory: web/
      - name: Install dependencies 📦
        run: yarn install --web-lockfile
        working-directory: web/
      - name: Download DB 📙
        run: |
          yarn global add zx
          ./scripts/download.mjs
      - name: Build web 🚧
        run: yarn run generate
        working-directory: web/
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: web/
      - name: Run Playwright tests
        run: yarn playwright test
        working-directory: web/
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: web/playwright-report/
          retention-days: 30
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: web/dist/static/
